### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by Deepnerd** [CorpulentBrony/smutty.horse#1]
How to install this on a ubuntu vps step by step?

**Comment by CorpulentBrony** [comment]
Sorry, this repo isn't really meant for easy or straightforward installation on other systems.  A lot of customization is hardcoded in various files.  I try to abstract stuff as much as possible to configuration, but the aim of this project wasn't really to make it super easy to deploy.

Perhaps sometime in the future I can do this, but it won't be anytime soon.
